{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aks-app.fullname" . }}-pdb
  namespace: {{ .Values.namespace.name }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ include "aks-app.name" . }}
{{- end }}
