apiVersion: v1
kind: Service
metadata:
  name: aks-app-{{ .Release.Name }}-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: aks-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: aks-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
