apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-app.fullname" . }}-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "aks-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "aks-app.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
